"""Initial migration

Revision ID: fa7f910ff4ca
Revises: 
Create Date: 2025-08-30 21:22:19.736543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7f910ff4ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qrcode', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['qrcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('qrcode')

    # ### end Alembic commands ###
